server:
  port: 8080


logging:
  level:
    org.springframework: DEBUG


spring:
  messages:
    basename: messages
#  devtools:
#    livereload:
#      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
  security:
    user:
      name: user
      password: password
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"



